import { beforeEach, describe, expect, it, vi } from 'vitest'
vi.mock('../../persistence/repo',()=>({repo:{save:vi.fn().mockResolvedValue(undefined),load:vi.fn(),list:vi.fn().mockResolvedValue([])}}))
import { repo } from '../../persistence/repo'
import { sample } from '../../domain/__tests__/fixtures/v2Tournament'
import { useTournamentStore } from '../../store/tournamentStore'
import { createPreparationAutosave } from '../../store/autosave'
import { createPlanningOwnerBoundary } from '../planningOwnership'
beforeEach(()=>{vi.clearAllMocks();useTournamentStore.setState({current:sample(),status:'loaded',revision:0,editsEnabled:true,saveError:''})})
describe('route ownership boundary',()=>{
 it('awaits under-debounce capture edit before V2, freezes legacy edits, and freshly rereads on return',async()=> {const writer=createPreparationAutosave(useTournamentStore,repo);const enter=createPlanningOwnerBoundary(useTournamentStore,()=>writer,()=>true);useTournamentStore.getState().updatePair('c','a','Latest','Name');await enter('/v2/groups');expect(repo.save).toHaveBeenCalledTimes(1);expect(useTournamentStore.getState().current).toBeNull();expect(useTournamentStore.getState().editsEnabled).toBe(false);const v2=sample();v2.name='V2 save';vi.mocked(repo.load).mockResolvedValue(v2);await enter('/tournaments/t/groups');await useTournamentStore.getState().loadTournament('t');expect(useTournamentStore.getState().current!.name).toBe('V2 save');await writer.flush();expect(repo.save).toHaveBeenCalledTimes(1);writer.stop()})
 it('retains dirty capture and edit permission on failed flush; retry succeeds',async()=>{const writer=createPreparationAutosave(useTournamentStore,repo);const enter=createPlanningOwnerBoundary(useTournamentStore,()=>writer,()=>true);useTournamentStore.getState().updatePair('c','a','Retained','Name');vi.mocked(repo.save).mockRejectedValueOnce(new Error('denied'));await expect(enter('/v2/calendar')).rejects.toThrow('denied');expect(useTournamentStore.getState().current!.categories[0].pairs[0].player1).toBe('Retained');expect(useTournamentStore.getState().editsEnabled).toBe(true);await enter('/v2/calendar');expect(repo.save).toHaveBeenCalledTimes(2);writer.stop()})
 it('refuses to release V2 while pending/draft guard denies close, including legacy direct route',async()=>{const writer=createPreparationAutosave(useTournamentStore,repo);let release=false;const enter=createPlanningOwnerBoundary(useTournamentStore,()=>writer,()=>release);await enter('/v2/groups');await expect(enter('/tournaments/t/fixture')).rejects.toThrow();expect(useTournamentStore.getState().editsEnabled).toBe(false);release=true;await enter('/');expect(repo.list).toHaveBeenCalled();expect(useTournamentStore.getState().editsEnabled).toBe(true);writer.stop()})
})
